name: golang-test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/workflows/test.yaml"

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        name: Setup Go
        with:
          go-version: ${{ matrix.go }}

      - name: test
        run: go test -v ./...
